"""
-------------
Converts selected prime implicants into human-readable SOP / POS expressions
and optionally generates a Verilog assign statement.

Variable naming convention (positional, MSB-first):
  2-var: A, B
  3-var: A, B, C
  4-var: A, B, C, D
"""

VAR_NAMES = ["A", "B", "C", "D"]


# ---------------------------------------------------------------------------
# SOP
# ---------------------------------------------------------------------------

def group_to_product_term(group: frozenset[int], num_vars: int) -> str:
    """
    Convert a prime implicant group into a product term string.

    For each variable position, if all minterms in the group share the same
    bit value, that literal appears in the term. If the bit varies across
    minterms, the variable is eliminated.

    Examples:
        {0, 1} (2-var) → "A'"   (A=0 for both, B varies → eliminate B)
        {3, 7} (3-var) → "BC"   (B=1, C=1 for both; A varies)
    """
    minterms = sorted(group)
    term_literals = []

    for bit_pos in range(num_vars):
        shift = num_vars - 1 - bit_pos
        bit_values = set((m >> shift) & 1 for m in minterms)

        if len(bit_values) == 1:
            var = VAR_NAMES[bit_pos]
            val = bit_values.pop()
            term_literals.append(var if val == 1 else f"{var}'")

    return "".join(term_literals) if term_literals else "1"


def build_sop(
    selected_groups: list[frozenset[int]], num_vars: int
) -> str:
    """
    Build the minimized SOP expression string from selected prime implicants.

    Returns:
        A string like "AB' + A'C + BD" or "0" (empty ON-set) or "1" (all minterms).
    """
    if not selected_groups:
        return "0"

    terms = [group_to_product_term(g, num_vars) for g in selected_groups]

    # Deduplicate while preserving order
    seen, unique_terms = set(), []
    for t in terms:
        if t not in seen:
            seen.add(t)
            unique_terms.append(t)

    return " + ".join(unique_terms)


# ---------------------------------------------------------------------------
# POS
# ---------------------------------------------------------------------------

def build_pos(minterms: list[int], num_vars: int) -> str:
    """
    Build the minimized POS expression by computing the SOP of the complement
    (maxterms) and applying De Morgan's theorem textually.

    The complement ON-set = all minterms NOT in the given ON-set.
    We compute SOP of the complement, then negate:
      POS = NOT( SOP_of_complement )
    which gives us a sum-term (maxterm) representation.

    For simplicity, this returns the dual SOP in the format:
      (sum_term1)(sum_term2)...
    """
    all_minterms = list(range(2 ** num_vars))
    maxterms = [m for m in all_minterms if m not in minterms]

    if not maxterms:
        return "1"  # All minterms covered → function is always 1
    if not minterms:
        return "0"  # No minterms → function is always 0

    # Re-use the SOP solver on the complement
    from solver.implicants import find_prime_implicants, select_essential_implicants

    prime_imps = find_prime_implicants(maxterms, num_vars)
    selected, _ = select_essential_implicants(maxterms, prime_imps)

    sum_terms = []
    for group in selected:
        product = group_to_product_term(group, num_vars)
        # Convert product term to sum term via De Morgan:
        # A'B → (A + B')
        sum_term = _product_to_sum_term(product)
        sum_terms.append(f"({sum_term})")

    return "".join(sum_terms) if sum_terms else "1"


def _product_to_sum_term(product_term: str) -> str:
    """
    Convert a product term literal string to its De Morgan dual sum term.
    e.g. "A'B" → "A + B'"
    """
    literals = _parse_literals(product_term)
    dual = []
    for var, complemented in literals:
        dual.append(f"{var}'" if not complemented else var)
    return " + ".join(dual)


def _parse_literals(term: str) -> list[tuple[str, bool]]:
    """
    Parse a product term like "A'BC'" into a list of (variable, is_complemented).
    """
    result = []
    i = 0
    while i < len(term):
        var = term[i]
        i += 1
        complemented = i < len(term) and term[i] == "'"
        if complemented:
            i += 1
        result.append((var, complemented))
    return result


# ---------------------------------------------------------------------------
# Verilog export
# ---------------------------------------------------------------------------

def build_verilog(sop_expr: str, num_vars: int, output_name: str = "F") -> str:
    """
    Generate a Verilog assign statement from an SOP expression.

    Example output:
        // Auto-generated by K-Map Solver
        module kmap_output (
            input  wire A, B, C, D,
            output wire F
        );
            assign F = (~A & B) | (A & ~C);
        endmodule

    Converts:
        A' → ~A
        AB → (A & B)
        + → |
    """
    if sop_expr in ("0", "1"):
        verilog_expr = sop_expr
    else:
        terms = [t.strip() for t in sop_expr.split("+")]
        verilog_terms = [_product_to_verilog(t) for t in terms]
        verilog_expr = " | ".join(verilog_terms)

    var_names = VAR_NAMES[:num_vars]
    input_ports = ", ".join(var_names)
    input_decls = "\n    ".join(f"input  wire {v}," for v in var_names)

    return (
        f"// Auto-generated by K-Map Solver\n"
        f"module kmap_output (\n"
        f"    {input_decls}\n"
        f"    output wire {output_name}\n"
        f");\n"
        f"    assign {output_name} = {verilog_expr};\n"
        f"endmodule"
    )


def _product_to_verilog(term: str) -> str:
    """Convert a single product term like "A'B" to Verilog "(~A & B)"."""
    if term == "1":
        return "1"
    literals = _parse_literals(term)
    verilog_lits = [f"~{v}" if c else v for v, c in literals]
    if len(verilog_lits) == 1:
        return verilog_lits[0]
    return "(" + " & ".join(verilog_lits) + ")"